### ISSUE TITLE
0.9.4: error: no member named 'ref' in namespace 'boost'

### ISSUE THREAD

**Issue by AngryPenguinPL** [shundhammer/myrlyn#92]
During compilation I see this error:
```
 /builddir/build/BUILD/myrlyn-0.9.4-build/myrlyn-0.9.4/src/YQPkgHistoryDialog.cc:163:51: error: no member named 'ref' in namespace 'boost'
DEBUG util.py:459:    163 |                                            boost::ref( itemCollector ) );
DEBUG util.py:459:        |                                            ~~~~~~~^
DEBUG util.py:459:  1 error generated.
DEBUG util.py:459:  make[2]: *** [src/CMakeFiles/myrlyn.dir/build.make:794: src/CMakeFiles/myrlyn.dir/YQPkgHistoryDialog.cc.o] Error 1
```

Details:
myrlyn 0.9.4
boost 1.88.0
libzypp 17.36.6

**Comment by shundhammer** [comment]
As you can see [here](https://build.opensuse.org/package/show/system:packagemanager/myrlyn), it builds fine in its devel project for 15.6, 16.0, Factory, Factory_ARM. 

openSUSE:Factory uses boost-1.87 which does not cause this problem.

It wouldn't be the first time that boost stuff causes new problems in new versions. But I am not going to spend the rest of my Sunday debugging yet another weird C++ / Boost problem caused by their neverending incompatibilities with themselves.

If anybody is willing to submit a patch, fine with me.

**Comment by shundhammer** [comment]
Added one more include; maybe they rearranged them again, or a libzypp header used to include it indirectly, and now it doesn't do that anymore.

**Comment by AngryPenguinPL** [comment]
thanks for the fix. After adding it, I now have a slightly different compilation error, but I've found a solution.

Here's the error:
```
make[2]: Leaving directory '/builddir/build/BUILD/myrlyn-0.9.4-build/myrlyn-0.9.4/build'
DEBUG util.py:459:  /builddir/build/BUILD/myrlyn-0.9.4-build/myrlyn-0.9.4/src/YQPkgHistoryDialog.cc:162:36: error: no matching constructor for initialization of 'zypp::parser::HistoryLogReader'
DEBUG util.py:459:    162 |     zypp::parser::HistoryLogReader reader( FILENAME,
DEBUG util.py:459:        |                                    ^       ~~~~~~~~~
DEBUG util.py:459:    163 |                                            zypp::parser::HistoryLogReader::Options(),
DEBUG util.py:459:        |                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DEBUG util.py:459:    164 |                                            boost::ref( itemCollector ) );
DEBUG util.py:459:        |                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~
DEBUG util.py:459:  /usr/include/zypp/parser/HistoryLogReader.h:86:5: note: candidate constructor not viable: no known conversion from 'const reference_wrapper<YQPkgHistoryItemCollector>' to 'ProcessData' (aka 'function<bool (const shared_ptr<HistoryLogData> &)>') for 3rd argument
DEBUG util.py:459:     86 |     HistoryLogReader(Pathname historyFile_r, zypp::parser::HistoryLogReader::Options options_r, ProcessData callback_r );
DEBUG util.py:459:        |     ^                                                                                           ~~~~~~~~~~~~~~~~~~~~~~
DEBUG util.py:459:  /usr/include/zypp/parser/HistoryLogReader.h:66:18: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 3 were provided
DEBUG util.py:459:     66 |   class ZYPP_API HistoryLogReader
DEBUG util.py:459:        |                  ^~~~~~~~~~~~~~~~
DEBUG util.py:459:  1 error generated.
DEBUG util.py:459:  make[2]: *** [src/CMakeFiles/myrlyn.dir/build.make:794: src/CMakeFiles/myrlyn.dir/YQPkgHistoryDialog.cc.o] Error 1
```

the solution is commit, which I added #93.
I checked after using it, the compilation is correct and the application works without any problems.
